### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-dream-team-1#1]
[reporte.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-dream-team-1/files/6770842/reporte.pdf)

**Comment by Lissete7** [comment]
Calificación 19 puntos.

**Comment by josealfredo79** [comment]
Este reporte debe describir mas a detalle el procedimiento, para poder evaluar el trabajo, quien evaluo no esta siendo objetivo
