### ISSUE TITLE
reporte

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-dream-team-1#2]
[reporte conexicon base de datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-dream-team-1/files/6788422/reporte.conexicon.base.de.datos.pdf)

**Comment by Yeim1129** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Este trabajo no contiene los pies de las ilustraciones y la descripción de las actividades es muy corta

**Comment by josealfredo79** [comment]
No se puede revisar y evaluar un trabajo asi
